import Link from "next/link";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-2xl mx-auto px-6 py-16">
        <Link href="/" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
          ← Back
        </Link>
        <h1 className="text-3xl font-bold mt-8 mb-2">Privacy Policy</h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: March 12, 2026</p>

        <div className="prose prose-neutral dark:prose-invert max-w-none space-y-8 text-sm leading-relaxed">

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">1. What data we collect</h2>
            <p className="text-muted-foreground">
              When you use Vouch to sign or upload documents, we collect the following:
            </p>
            <ul className="list-disc list-inside space-y-1 text-muted-foreground">
              <li><span className="text-foreground font-medium">Name</span> — provided during passkey registration, embedded in signed documents.</li>
              <li><span className="text-foreground font-medium">Passkey credential</span> — a cryptographic public key and credential ID generated by your device. We never receive your biometric data.</li>
              <li><span className="text-foreground font-medium">Document content</span> — the PDF files uploaded for signing, stored in Supabase Storage.</li>
              <li><span className="text-foreground font-medium">Document hash and cryptographic signature</span> — a SHA-256 hash of each signed document and its post-quantum signature, stored alongside the signing session.</li>
              <li><span className="text-foreground font-medium">IP address</span> — recorded at the time of signing for security and fraud prevention purposes.</li>
              <li><span className="text-foreground font-medium">Event logs</span> — timestamped records of signing events (e.g., <code>signature_applied</code>) used to maintain an audit trail.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">2. Why we collect it</h2>
            <p className="text-muted-foreground">
              All data is collected solely to provide the Vouch document-signing service: authenticating signers, producing legally binding electronic signatures, and allowing document owners to verify the integrity of signed documents.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">3. Data retention</h2>
            <ul className="list-disc list-inside space-y-1 text-muted-foreground">
              <li>Documents and cryptographic signatures are retained indefinitely unless the document owner explicitly deletes them.</li>
              <li>IP address logs and signing event logs are retained for <span className="text-foreground font-medium">90 days</span>, after which they are purged.</li>
              <li>Passkey credentials remain registered until you remove them.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">4. Third-party infrastructure</h2>
            <p className="text-muted-foreground">
              We use <span className="text-foreground font-medium">Supabase</span> as our database and file storage provider. Your data is stored on Supabase infrastructure and subject to{" "}
              <a href="https://supabase.com/privacy" target="_blank" rel="noopener noreferrer" className="underline hover:text-foreground">
                Supabase&apos;s privacy policy
              </a>. We do not sell or share your data with any other third parties.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">5. Your rights</h2>
            <p className="text-muted-foreground">
              You have the right to request access to, correction of, or deletion of your personal data. To exercise these rights, contact us at{" "}
              <a href="mailto:hello@vouch.so" className="underline hover:text-foreground">hello@vouch.so</a>.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">6. Contact</h2>
            <p className="text-muted-foreground">
              Questions about this policy?{" "}
              <a href="mailto:hello@vouch.so" className="underline hover:text-foreground">hello@vouch.so</a>
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
